---
- name: Playbook de build da imagem rodrigobrim/centos8
  hosts: localhost
  connection: local
  collections:
    - rodrigobrim.packer_vagrant_images

  roles:
    - role: rodrigobrim.packer_vagrant_images.virtualbox_build
      vars:
        virtualbox_build_path: "{{ ansible_env.PWD }}"
        virtualbox_build_username: "{{ vagrant_cloud_username }}"
        virtualbox_build_box_name: "{{ box_name }}"
        virtualbox_build_json: "{{ packer_build_vagrant_json }}"
