---
box_basename: "{{ name }}-{{ image_architecture }}"
box_name: centos8
build_directory: builds
cpus: 1
disk_size: 30720
headless: "true"
http_directory: kickstart/
image_version: 8.2.2004
image_architecture: x86_64
iso_checksum: "sha256:c87a2d81d67bbaeaf646aea5bedd70990078ec252fc52f5a7d65ff609871e255"
iso_name: CentOS-{{ image_version }}-{{ image_architecture }}-dvd1
iso_urls:
  - "~/Downloads/isos/{{ iso_name }}/{{ iso_name }}.iso"
  - "{{ iso_name }}.iso"
  - "{{ mirror_url }}"
ks_path: ks.cfg
memory: 1024
mirror: http://mirrors.kernel.org/centos
mirror_directory: "{{ image_version }}/isos/{{ image_architecture }}"
mirror_url: "{{ mirror }}/{{ image_version }}/isos/{{ image_architecture }}/{{ iso_name }}.iso"
name: centos-8.2
packer_build_vagrant_json: packer-config.json
playbooks_dir: playbooks
script_dir: scripts
vagrant_cloud_username: rodrigobrim
